services:
  postgres:
    image: postgres:17.2-alpine
    container_name: postgres
    env_file: .env

  django:
    build:
      context: ./vr_movement_research
    container_name: django
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    env_file: .env
    volumes:
      - static_volume:/app/static
    restart: on-failure:5

  nginx:
    image: nginx:1.27-alpine-slim
    container_name: nginx
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
      - static_volume:/static
    ports:
      - "80:80"
    depends_on:
      - django

volumes:
  static_volume: