# Generated by Django 5.2 on 2025-05-04 20:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExperimentSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deviceName', models.CharField(max_length=255, verbose_name='Название устройства')),
                ('sessionTotalTime', models.FloatField(verbose_name='Общее время сессии')),
                ('personAge', models.IntegerField(verbose_name='Возраст')),
                ('personExperienceInVR', models.IntegerField(help_text='В часах', verbose_name='Опыт в VR')),
                ('comments', models.TextField(blank=True, null=True, verbose_name='Комментарии')),
            ],
            options={
                'verbose_name': 'Сессия',
                'verbose_name_plural': 'Сессии',
            },
        ),
        migrations.CreateModel(
            name='LocomotionPreset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isTopTime', models.BooleanField(default=False)),
                ('time', models.FloatField(blank=True, null=True, verbose_name='Время использования')),
                ('allowScreenFading', models.BooleanField(verbose_name='Затемнение экрана')),
                ('screenFadingMask', models.IntegerField(verbose_name='Маска')),
                ('screenFadingSpeed', models.FloatField(verbose_name='Скорость затемнения')),
                ('screenFadingAlpha', models.FloatField(verbose_name='Прозрачность затемнения')),
                ('movementSpeed', models.FloatField(verbose_name='Скорость передвижения')),
                ('allowHandDirection', models.BooleanField(verbose_name='Рука указывает направление')),
                ('handChoice', models.IntegerField(help_text='0-левая, 1-правая', verbose_name='Рука')),
                ('allowScreenShaking', models.BooleanField(verbose_name='Покачивание экрана')),
                ('screenShakingAmplitude', models.FloatField(verbose_name='Амплитуда покачивания')),
                ('screenShakingSpeed', models.FloatField(verbose_name='Скорость покачивания')),
                ('experimentSession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='get_data.experimentsession', verbose_name='Сессия')),
            ],
            options={
                'verbose_name': 'Настройки плавного передвижения',
                'verbose_name_plural': 'Настройки плавного передвижения',
            },
        ),
        migrations.CreateModel(
            name='RotationPreset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isTopTime', models.BooleanField(default=False)),
                ('time', models.FloatField(blank=True, null=True, verbose_name='Время использования')),
                ('allowScreenFading', models.BooleanField(verbose_name='Затемнение экрана')),
                ('screenFadingMask', models.IntegerField(verbose_name='Маска')),
                ('screenFadingSpeed', models.FloatField(verbose_name='Скорость затемнения')),
                ('screenFadingAlpha', models.FloatField(verbose_name='Прозрачность затемнения')),
                ('rotationType', models.IntegerField(verbose_name='Тип вращения')),
                ('smoothRotationSpeed', models.FloatField(verbose_name='Скорость плавного вращения')),
                ('snapRotationAngle', models.FloatField(verbose_name='Угол резкого вращения')),
                ('snapRotationDelay', models.FloatField(verbose_name='Задержка резкого вращения')),
                ('allowDashRotation', models.BooleanField(verbose_name='Вращение рывком')),
                ('shiftType', models.IntegerField(help_text='0-линейное вращение, 1-вразение с ускорением', verbose_name='Режим вращения рывком')),
                ('linearShiftSpeed', models.FloatField(verbose_name='Линейная скорость')),
                ('smoothDampShiftSpeed', models.FloatField(verbose_name='Скорость с ускорением')),
                ('experimentSession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='get_data.experimentsession', verbose_name='Сессия')),
            ],
            options={
                'verbose_name': 'Настройки вращения',
                'verbose_name_plural': 'Настройки вращения',
            },
        ),
        migrations.CreateModel(
            name='TeleportationPreset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isTopTime', models.BooleanField(default=False)),
                ('time', models.FloatField(blank=True, null=True, verbose_name='Время использования')),
                ('allowScreenFading', models.BooleanField(verbose_name='Затемнение экрана')),
                ('screenFadingMask', models.IntegerField(verbose_name='Маска')),
                ('screenFadingSpeed', models.FloatField(verbose_name='Скорость затемнения')),
                ('screenFadingAlpha', models.FloatField(verbose_name='Прозрачность затемнения')),
                ('teleportationDelay', models.FloatField(verbose_name='Задержка телепортации')),
                ('allowDashTeleportation', models.BooleanField(verbose_name='Телепортация рывком')),
                ('shiftType', models.IntegerField(help_text='0-линейное перемещение, 1-перемещение с ускорением', verbose_name='Режим перемещения')),
                ('linearShiftSpeed', models.FloatField(verbose_name='Линейная скорость')),
                ('smoothDampShiftSpeed', models.FloatField(verbose_name='Скорость с ускорением')),
                ('experimentSession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='get_data.experimentsession', verbose_name='Сессия')),
            ],
            options={
                'verbose_name': 'Настройки телепортации',
                'verbose_name_plural': 'Настройки телепортации',
            },
        ),
    ]
