# Generated by Django 4.2.16 on 2024-11-30 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LocomotionPresets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('movementSpeed', models.FloatField()),
                ('allowHandDirection', models.BooleanField()),
                ('handChoice', models.IntegerField(null=True)),
                ('allowScreenShaking', models.BooleanField()),
                ('screenShakingAmplitude', models.FloatField(null=True)),
                ('screenShakingSpeed', models.FloatField(null=True)),
                ('allowScreenFading', models.BooleanField()),
                ('screenFadingMask', models.IntegerField(null=True)),
                ('screenFadingSpeed', models.FloatField(null=True)),
                ('screenFadingAlpha', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RotationPresets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('rotationType', models.IntegerField()),
                ('smoothRotationSpeed', models.FloatField(null=True)),
                ('snapRotationAngle', models.FloatField(null=True)),
                ('snapRotationDelay', models.FloatField(null=True)),
                ('allowDashRotation', models.BooleanField(null=True)),
                ('shiftType', models.IntegerField(null=True)),
                ('linearShiftSpeed', models.FloatField(null=True)),
                ('smoothDampShiftSpeed', models.FloatField(null=True)),
                ('allowScreenFading', models.BooleanField()),
                ('screenFadingMask', models.IntegerField(null=True)),
                ('screenFadingSpeed', models.FloatField(null=True)),
                ('screenFadingAlpha', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TeleportationPresets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('teleportationDelay', models.FloatField()),
                ('allowDashTeleportation', models.BooleanField()),
                ('shiftType', models.IntegerField(null=True)),
                ('linearShiftSpeed', models.FloatField(null=True)),
                ('smoothDampShiftSpeed', models.FloatField(null=True)),
                ('allowScreenFading', models.BooleanField()),
                ('screenFadingMask', models.IntegerField(null=True)),
                ('screenFadingSpeed', models.FloatField(null=True)),
                ('screenFadingAlpha', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PresetUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('locomotionPresets', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='get_data.locomotionpresets')),
                ('rotationPresets', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='get_data.rotationpresets')),
                ('teleportationPresets', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='get_data.teleportationpresets')),
            ],
        ),
    ]
