# Generated by Django 5.2 on 2025-05-26 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('get_data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locomotionpreset',
            name='allowHandDirection',
            field=models.BooleanField(blank=True, null=True, verbose_name='Рука указывает направление'),
        ),
        migrations.AlterField(
            model_name='locomotionpreset',
            name='allowScreenShaking',
            field=models.BooleanField(blank=True, null=True, verbose_name='Покачивание экрана'),
        ),
        migrations.AlterField(
            model_name='locomotionpreset',
            name='handChoice',
            field=models.IntegerField(blank=True, help_text='0-левая, 1-правая', null=True, verbose_name='Рука'),
        ),
        migrations.AlterField(
            model_name='locomotionpreset',
            name='screenFadingAlpha',
            field=models.FloatField(blank=True, null=True, verbose_name='Прозрачность затемнения'),
        ),
        migrations.AlterField(
            model_name='locomotionpreset',
            name='screenFadingMask',
            field=models.IntegerField(blank=True, null=True, verbose_name='Маска'),
        ),
        migrations.AlterField(
            model_name='locomotionpreset',
            name='screenFadingSpeed',
            field=models.FloatField(blank=True, null=True, verbose_name='Скорость затемнения'),
        ),
        migrations.AlterField(
            model_name='locomotionpreset',
            name='screenShakingAmplitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Амплитуда покачивания'),
        ),
        migrations.AlterField(
            model_name='locomotionpreset',
            name='screenShakingSpeed',
            field=models.FloatField(blank=True, null=True, verbose_name='Скорость покачивания'),
        ),
        migrations.AlterField(
            model_name='rotationpreset',
            name='allowDashRotation',
            field=models.BooleanField(blank=True, null=True, verbose_name='Вращение рывком'),
        ),
        migrations.AlterField(
            model_name='rotationpreset',
            name='linearShiftSpeed',
            field=models.FloatField(blank=True, null=True, verbose_name='Линейная скорость'),
        ),
        migrations.AlterField(
            model_name='rotationpreset',
            name='screenFadingAlpha',
            field=models.FloatField(blank=True, null=True, verbose_name='Прозрачность затемнения'),
        ),
        migrations.AlterField(
            model_name='rotationpreset',
            name='screenFadingMask',
            field=models.IntegerField(blank=True, null=True, verbose_name='Маска'),
        ),
        migrations.AlterField(
            model_name='rotationpreset',
            name='screenFadingSpeed',
            field=models.FloatField(blank=True, null=True, verbose_name='Скорость затемнения'),
        ),
        migrations.AlterField(
            model_name='rotationpreset',
            name='shiftType',
            field=models.IntegerField(blank=True, help_text='0-линейное вращение, 1-вразение с ускорением', null=True, verbose_name='Режим вращения рывком'),
        ),
        migrations.AlterField(
            model_name='rotationpreset',
            name='smoothDampShiftSpeed',
            field=models.FloatField(blank=True, null=True, verbose_name='Скорость с ускорением'),
        ),
        migrations.AlterField(
            model_name='rotationpreset',
            name='smoothRotationSpeed',
            field=models.FloatField(blank=True, null=True, verbose_name='Скорость плавного вращения'),
        ),
        migrations.AlterField(
            model_name='rotationpreset',
            name='snapRotationAngle',
            field=models.FloatField(blank=True, null=True, verbose_name='Угол резкого вращения'),
        ),
        migrations.AlterField(
            model_name='rotationpreset',
            name='snapRotationDelay',
            field=models.FloatField(blank=True, null=True, verbose_name='Задержка резкого вращения'),
        ),
        migrations.AlterField(
            model_name='teleportationpreset',
            name='linearShiftSpeed',
            field=models.FloatField(blank=True, null=True, verbose_name='Линейная скорость'),
        ),
        migrations.AlterField(
            model_name='teleportationpreset',
            name='screenFadingAlpha',
            field=models.FloatField(blank=True, null=True, verbose_name='Прозрачность затемнения'),
        ),
        migrations.AlterField(
            model_name='teleportationpreset',
            name='screenFadingMask',
            field=models.IntegerField(blank=True, null=True, verbose_name='Маска'),
        ),
        migrations.AlterField(
            model_name='teleportationpreset',
            name='screenFadingSpeed',
            field=models.FloatField(blank=True, null=True, verbose_name='Скорость затемнения'),
        ),
        migrations.AlterField(
            model_name='teleportationpreset',
            name='shiftType',
            field=models.IntegerField(blank=True, help_text='0-линейное перемещение, 1-перемещение с ускорением', null=True, verbose_name='Режим перемещения'),
        ),
        migrations.AlterField(
            model_name='teleportationpreset',
            name='smoothDampShiftSpeed',
            field=models.FloatField(blank=True, null=True, verbose_name='Скорость с ускорением'),
        ),
    ]
