# Generated by Django 4.2.4 on 2024-12-16 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('get_data', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LocomotionPresets',
            new_name='LocomotionPreset',
        ),
        migrations.RenameModel(
            old_name='RotationPresets',
            new_name='RotationPreset',
        ),
        migrations.RenameModel(
            old_name='TeleportationPresets',
            new_name='TeleportationPreset',
        ),
        migrations.RenameField(
            model_name='presetusers',
            old_name='locomotionPresets',
            new_name='locomotionPreset',
        ),
        migrations.RenameField(
            model_name='presetusers',
            old_name='rotationPresets',
            new_name='rotationPreset',
        ),
        migrations.RenameField(
            model_name='presetusers',
            old_name='teleportationPresets',
            new_name='teleportationPreset',
        ),
    ]
