# Generated by Django 5.2 on 2025-04-30 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('get_data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locomotionpreset',
            name='isTopTime',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='rotationpreset',
            name='isTopTime',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='teleportationpreset',
            name='isTopTime',
            field=models.BooleanField(default=False),
        ),
    ]
