# Generated by Django 5.2 on 2025-04-07 20:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('get_data', '0002_rename_locomotionpresets_locomotionpreset_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExperimentSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deviceName', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='locomotionpreset',
            name='time',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='rotationpreset',
            name='time',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='teleportationpreset',
            name='time',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='locomotionpreset',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='rotationpreset',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='teleportationpreset',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='locomotionpreset',
            name='experimentSession_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lastLocomotionPreset', to='get_data.experimentsession'),
        ),
        migrations.AddField(
            model_name='locomotionpreset',
            name='experimentSession_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='topTimeLocomotionPresets', to='get_data.experimentsession'),
        ),
        migrations.AddField(
            model_name='rotationpreset',
            name='experimentSession_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lastRotationPreset', to='get_data.experimentsession'),
        ),
        migrations.AddField(
            model_name='rotationpreset',
            name='experimentSession_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='topTimeRotationPresets', to='get_data.experimentsession'),
        ),
        migrations.AddField(
            model_name='teleportationpreset',
            name='experimentSession_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lastTeleportationPreset', to='get_data.experimentsession'),
        ),
        migrations.AddField(
            model_name='teleportationpreset',
            name='experimentSession_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='topTimeTeleportationPresets', to='get_data.experimentsession'),
        ),
        migrations.DeleteModel(
            name='PresetUsers',
        ),
    ]
