# Generated by Django 5.2 on 2025-04-07 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('get_data', '0003_experimentsession_locomotionpreset_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locomotionpreset',
            name='movementSpeed',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='teleportationpreset',
            name='teleportationDelay',
            field=models.FloatField(null=True),
        ),
    ]
