# Generated by Django 5.2 on 2025-04-07 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('get_data', '0004_alter_locomotionpreset_movementspeed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='experimentsession',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
    ]
