# Generated by Django 5.2 on 2025-04-07 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('get_data', '0005_experimentsession_comments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='experimentsession',
            old_name='comments',
            new_name='comment',
        ),
    ]
